services:
  - type: web
    name: flipkart-price-tracker
    env: python
    buildCommand: bash setup.sh && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
